
🧾 PHP Syntax
PHP has its own set of rules and structure—called syntax—that tells the server how to interpret your code. Understanding syntax is essential for writing valid and working PHP scripts.

✅ Basic Structure of a PHP Script
Every PHP script starts with <?php 'and ends with' ?>. Everything in between is treated as PHP code.


<?php
// Your PHP code goes here
echo "Hello, world!";
?>
🔹 The <?php 'opening tag tells the server to start processing PHP code.
🔹 The closing' ?> tag is optional if the PHP file contains only PHP code.

📌 Key Syntax Rules
Statements end with a semicolon ;


echo "Hello!"; // Correct
PHP is case-insensitive for keywords, but variables are case-sensitive


ECHO "Hello";  // Works
echo "World";  // Works
$name = "John";
echo $Name;    // Error – $Name is not the same as $name
Use comments to annotate your code

// or # for single-line comments

/* */ for multi-line comments

🔄 Mixing PHP with HTML
PHP is often embedded inside HTML. This is what makes PHP great for web development.


<!DOCTYPE html>
<html>
<head><title>PHP Page</title></head>
<body>

<h1>Welcome!</h1>
<p>
    <?php
    echo "This text is generated by PHP!";
    ?>
</p>

</body>
</html>
⚠️ Common Syntax Mistakes
Forgetting a semicolon ; at the end of a line

Using wrong quotation marks or mismatching them

Misspelling variables or functions

Not closing brackets {}, [], () properly

🧪 Quick Practice

<?php
$name = "Alice";
echo "Hello, " . $name . "!";
?>
What this does:

Declares a variable $name

Uses echo to output a greeting

